pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./adding-custom-metadata-to-your.html","Adding custom metadata to your project","Adding custom metadata to your project Navigation: No topics above this level Adding custom metadata to your project The Template Manager allows y...",""],
["./advanced-match-options-tab.html","Advanced Match Options Tab","Advanced Match Options Tab Navigation: No topics above this level Advanced Match Options Tab ",""],
["./configuration-guide.html","Configuration Guide","Configuration Guide Navigation: No topics above this level Configuration Guide After installing the application and running it you will be require...",""],
["./controls-bar.html","Controls Bar","Controls Bar Navigation: No topics above this level Controls Bar Each of the features shown by the Controls Bar will be explained in more detail l...",""],
["./creating--saving-template-docu.html","Creating &#38; Saving Template Documents","Creating &#38; Saving Template Documents Navigation: No topics above this level Creating &#38; Saving Template Documents 1.Open a new or existing Word or ...",""],
["./custom-prompt-fields.html","Custom prompt fields","Custom prompt fields Navigation: No topics above this level Custom prompt fields 1.Select the Custom Prompt Field button to show the relevant cont...",""],
["./custom-prompt-template-fields.html","Custom Prompt Template Fields","Custom Prompt Template Fields Navigation: No topics above this level Custom Prompt Template Fields These fields are used to prompt the user for in...",""],
["./initial-run.html","Initial Run","Initial Run Navigation: No topics above this level Initial Run On first run, the application will load your Clients and Jobs lists and store them ...",""],
["./merging-templates-with-client-.html","Merging Templates with Client and Job Data","Merging Templates with Client and Job Data Navigation: No topics above this level Merging Templates with Client and Job Data The main purpose of t...",""],
["./saving-your-template.html","Saving Your Template","Saving Your Template Navigation: No topics above this level Saving Your Template Once your template is ready it needs to be saved to the Modern Pr...",""],
["./settings-tab.html","Settings Tab","Settings Tab Navigation: No topics above this level Settings Tab Here you are prompted to enter the folder where your scanner saves its output pdf...",""],
["./sharepoint-tab.html","SharePoint Tab","SharePoint Tab Navigation: No topics above this level SharePoint Tab \\\\ On the SharePoint Tab you are prompted to enter the URL of your Modern Pra...",""],
["./standard-template-fields.html","Standard Template Fields","Standard Template Fields Navigation: No topics above this level Standard Template Fields Standard Template fields are used to merge Xero Practice ...",""],
["./standard-template-fields2.html","Standard Template Fields","Standard Template Fields Navigation: No topics above this level Standard Template Fields 1.Select the type of field you want to use from the 3 but...",""],
["./the-software.html","The Software","The Software Navigation: No topics above this level The Software Template Manager is installed as default on the home page of your OnePractice Doc...",""],
["./themes.html","Themes","Themes Navigation: No topics above this level Themes The Template Manager is SharePoint Theme enabled. If you change your theme in Office365 Share...",""],
["./usign-drag--drop.html","Using Drag &#38; Drop","Using Drag &#38; Drop Navigation: No topics above this level Using Drag &#38; Drop Once you are ready to save your newly created template, you can simply ...",""],
["./using-the-template-field-build.html","Using the Template Field Builder","Using the Template Field Builder Navigation: No topics above this level Using the Template Field Builder All of the above fields can be constructe...",""],
["./word-equivalency-tab.html","Word Equivalency Tab","Word Equivalency Tab Navigation: No topics above this level Word Equivalency Tab Here you are able to enter as many Word Equivalents as you please...",""],
["./workflowmax-tab.html","WorkflowMax Tab","WorkflowMax Tab Navigation: No topics above this level WorkflowMax Tab Here you are prompted to enter your WorkflowMax Account Key which HubOne wi...",""]];
