pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./adding-custom-metadata-to-your.html","Adding custom metadata to your project","Adding custom metadata to your project Navigation: No topics above this level Adding custom metadata to your project The Template Manager allows y...",""],
["./advanced-match-options-tab.html","Advanced Match Options Tab","Advanced Match Options Tab Navigation: No topics above this level Advanced Match Options Tab Enter the number of characters in a Client Name with ...",""],
["./configuration-guide.html","Configuration Guide","Configuration Guide Navigation: No topics above this level Configuration Guide After installing the application and running it you will be require...",""],
["./controls-bar.html","Controls Bar","Controls Bar Navigation: No topics above this level Controls Bar Each of the features shown by the Controls Bar will be explained in more detail l...",""],
["./creating--saving-template-docu.html","Creating &#38; Saving Template Documents","Creating &#38; Saving Template Documents Navigation: No topics above this level Creating &#38; Saving Template Documents 1.Open a new or existing Word or ...",""],
["./custom-prompt-fields.html","Custom prompt fields","Custom prompt fields Navigation: No topics above this level Custom prompt fields 1.Select the Custom Prompt Field button to show the relevant cont...",""],
["./custom-prompt-template-fields.html","Custom Prompt Template Fields","Custom Prompt Template Fields Navigation: No topics above this level Custom Prompt Template Fields These fields are used to prompt the user for in...",""],
["./example-1.html","Example 1","Example 1 Navigation: No topics above this level Example 1 Let’s say for example we want to have a renaming rule that prepends the Tax Year to the...",""],
["./example-2.html","Example 2","Example 2 Navigation: No topics above this level Example 2 What if we wanted to add the custom text &#8220;Archive&#8221; to the front of each of a particular...",""],
["./expporting-and-importing-setti.html","Exporting and Importing Settings","Exporting and Importing Settings Navigation: No topics above this level Exporting and Importing Settings Once your settings are complete and valid...",""],
["./file-logs.html","File Logs","File Logs Navigation: No topics above this level File Logs The directory you have selected to scan will contain 2 folders. These are &#8220;UploadComple...",""],
["./file-rename-options-tab.html","File Rename Options Tab","File Rename Options Tab Navigation: No topics above this level File Rename Options Tab This panel gives you the option to add file renaming rules....",""],
["./initial-run.html","Initial Run","Initial Run Navigation: No topics above this level Initial Run On first run, the application will load your Clients and Jobs lists and store them ...",""],
["./manual-mode-processing.html","Manual Mode Processing","Manual Mode Processing Navigation: No topics above this level Manual Mode Processing If you have selected Manual Mode in the settings the software...",""],
["./merging-templates-with-client-.html","Merging Templates with Client and Job Data","Merging Templates with Client and Job Data Navigation: No topics above this level Merging Templates with Client and Job Data The main purpose of t...",""],
["./sample-templates.html","Sample Templates","Sample Templates Navigation: No topics above this level Sample Templates Enter topic text here. ",""],
["./saving-your-template.html","Saving Your Template","Saving Your Template Navigation: No topics above this level Saving Your Template Once your template is ready it needs to be saved to the Modern Pr...",""],
["./scanned-document-manager.html","Scanned Document Manager","Scanned Document Manager Navigation: No topics above this level Scanned Document Manager Click to download Scanned Document Manager Guide The HubO...",""],
["./settings-tab.html","Settings Tab","Settings Tab Navigation: No topics above this level Settings Tab Here you are prompted to enter the folder where your scanner saves its output pdf...",""],
["./sharepoint-tab.html","SharePoint Tab","SharePoint Tab Navigation: No topics above this level SharePoint Tab \\\\ On the SharePoint Tab you are prompted to enter the URL of your Modern Pra...",""],
["./standard-template-fields.html","Standard Template Fields","Standard Template Fields Navigation: No topics above this level Standard Template Fields Standard Template fields are used to merge Xero Practice ...",""],
["./standard-template-fields2.html","Standard Template Fields","Standard Template Fields Navigation: No topics above this level Standard Template Fields 1.Select the type of field you want to use from the 3 but...",""],
["./template-manager.html","Template Manager","Template Manager Navigation: No topics above this level Template Manager Download the Template Manager Guide The Template Manager facilitates powe...",""],
["./the-settings-are-ready.html","The Settings are Ready!","The Settings are Ready! Navigation: No topics above this level The Settings are Ready! Once all settings are valid and the Save Button on the bott...",""],
["./the-software.html","The Software","The Software Navigation: No topics above this level The Software Template Manager is installed as default on the home page of your OnePractice Doc...",""],
["./themes.html","Themes","Themes Navigation: No topics above this level Themes The Template Manager is SharePoint Theme enabled. If you change your theme in Office365 Share...",""],
["./user-guide.html","User Guide","User Guide Navigation: No topics above this level User Guide Once your settings are complete and valid and you have clicked the Refresh Button on ...",""],
["./usign-drag--drop.html","Using Drag &#38; Drop","Using Drag &#38; Drop Navigation: No topics above this level Using Drag &#38; Drop Once you are ready to save your newly created template, you can simply ...",""],
["./using-the-file-name-builder-to.html","Using the FIle Name Builder Tool","Using the FIle Name Builder Tool Navigation: No topics above this level Using the FIle Name Builder Tool Access the handy File Name Builder tool b...",""],
["./using-the-template-field-build.html","Using the Template Field Builder","Using the Template Field Builder Navigation: No topics above this level Using the Template Field Builder All of the above fields can be constructe...",""],
["./word-equivalency-tab.html","Word Equivalency Tab","Word Equivalency Tab Navigation: No topics above this level Word Equivalency Tab Here you are able to enter as many Word Equivalents as you please...",""],
["./workflowmax-tab.html","WorkflowMax Tab","WorkflowMax Tab Navigation: No topics above this level WorkflowMax Tab Here you are prompted to enter your WorkflowMax Account Key which HubOne wi...",""]];
